# This is a basic workflow to help you get started with Actions

name: Build and publish blog

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: latest
          
        
      - name: Install Hexo
        run: |
          corepack enable
          npm install -g hexo-cli
      
      - name: Build page
        run: |
          yarn install
          hexo generate
      
      - name: Upload to qiniu
        uses: bonaysoft/uptoc@v1.4.3
        with:
          driver: qiniu
          region: cn-east-1
          bucket: dianhsu-blog
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_AK }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SK }}
